COPY (SELECT
    building_id,
    ref_toid,
    ref_osm_id,
    revision_id,
    location_name,
    location_number,
    location_street,
    location_line_two,
    location_town,
    location_postcode,
    location_latitude,
    location_longitude,
    ext_predominant_land_use,
    ext_designated_land_use,
    ext_avg_bld_density,
    ext_avg_bld_distance,
    date_year,
    ext_age_year_demolition,
    ext_age_year_renovation,
    ext_heritage_zoning,
    ext_historical_notes,
    ext_footprintsize,
    ext_plotsize,
    size_height_apex,
    ext_far_ratio,
    size_storeys_core,
    ext_building_quality,
    ext_gardens,
    ext_greenwalls,
    construction_core_material,
    ext_solarpanels,
    ext_pool,
    ext_walk_index,
    ext_num_trees_within_100,
    ext_greenspace_proximity,
    ext_nabers_energy_rating,
    ext_electricity,
    ext_water
FROM buildings)
TO '/tmp/building_attributes.csv'
WITH CSV HEADER
